name: Build and Deploy

on:
  push:
    branches:
      - main  # Zmień na wybraną gałąź
  pull_request:
    branches:
      - main  # Zmień na wybraną gałąź

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Zmień na odpowiednią wersję Node.js

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build  # Zmień na odpowiednią komendę budowania

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Zmień na odpowiednią ścieżkę do folderu zbudowanej aplikacji
