name: Build and Deploy

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.UBERSHMEKEL_ALT_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'  
          distribution: 'temurin'
          cache: maven

      - name: Build
        run:  mvn -B package --file pom.xml